import re

todo = """
"IronSmelting"
"CopperSmelting"
"SiliconSmelting"
"StoneSmelting"
"GraphiteSmelting"
"PlasmaRefining"
"Plastic"
"GrapheneFromFireIce"
"GrapheneFromGraphiteAndSulfuric"
"MagnetSmelting"
"Electromagnet"
"CrystalSiliconFromIngot"
"CrystalSiliconFromFractal"
"GlassSmelting"
"DiamondFromGraphite"
"DiamondFromKimberlite"
"XRayCracking"
"OrganicCrystalFromWood"
"OrganicCrystalFromPlastic"
"HydrogenFuelRod"
"SteelSmelting"
"SiliconOreFromStone"
"CircuitBoard"
"SulfuricAcidFromStone"
"PlasmaExciter"
"Processor"
"PhotonCombinerFromPrism"
"PhotonCombinerFromCrystal"
"MicrocrystallineComponent"
"ElectromagneticMatrix"
"EnergyMatrix"
"Foundation"
"TeslaTower"
"WirelessPowerTower"
"WindTurbine"
"ThermalPowerStation"
"SolarPanel"
"ConveyorMK1"
"Splitter"
"StorageMK1"
"FluidStorage"
"SorterMK1"
"SorterMK2"
"MiningMachine"
"WaterPump"
"OilExtractor"
"OilRefinery"
"AssemblingMachineMK1"
"Smelter"
"Fractionator"
"ChemicalPlant"
"MatrixLab"
"""

regex = re.compile(r'([A-Z][a-z]*)(?=[A-Z])')

for line in todo.splitlines():
    print(regex.sub("\\1 ", line))
