// Maybe in the future this will be translated to other languages.

import { Item, Producer, Recipe, Technology } from "../dsp";

export const English = {
    items: {
        "IronOre": "Iron Ore",
        "CopperOre": "Copper Ore",
        "StoneOre": "Stone Ore",
        "CoalOre": "Coal Ore",
        "SiliconOre": "Silicon Ore",
        "TungstenOre": "Tungsten Ore",
        "Water": "Water",
        "CrudeOil": "Crude Oil",
        "Hydrogen": "Hydrogen",
        "Deuterium": "Deuterium",
        "Antimatter": "Antimatter",
        "Kimberlite": "Kimberlite",
        "IronIngot": "Iron Ingot",
        "CopperIngot": "Copper Ingot",
        "StoneBrick": "Stone Brick",
        "EnergeticGraphite": "Energetic Graphite",
        "HighPuritySilicon": "High Purity Silicon",
        "TungstenIngot": "Tungsten Ingot",
        "SufuricAcid": "Sufuric Acid",
        "RefinedOil": "Refined Oil",
        "HydrogenFuelRod": "Hydrogen Fuel Rod",
        "DeuteronFuelRod": "Deuteron Fuel Rod",
        "AntimatterFuelRod": "Antimatter Fuel Rod",
        "FractalSilicon": "Fractal Silicon",
        "Magnet": "Magnet",
        "Electromagnet": "Electromagnet",
        "Glass": "Glass",
        "Diamond": "Diamond",
        "CrystalSilicon": "Crystal Silicon",
        "TitaniumAlloy": "Titanium Alloy",
        "FireIce": "Fire Ice",
        "Plastic": "Plastic",
        "OrganicCrystal": "Organic Crystal",
        "Graphene": "Graphene",
        "Thruster": "Thruster",
        "OpticalGratingCrystal": "Optical Grating Crystal",
        "Steel": "Steel",
        "CircuitBoard": "Circuit Board",
        "Prism": "Prism",
        "Motor": "Motor",
        "MicrocrystallineComponent": "Microcrystalline Component",
        "CasimirCrystal": "Casimir Crystal",
        "StrangeMatter": "Strange Matter",
        "TitaniumCrystal": "Titanium Crystal",
        "CarbonNanotube": "Carbon Nanotube",
        "ReinforcedThruster": "Reinforced Thruster",
        "SpiniformStalagmiteCrystal": "Spiniform Stalagmite Crystal",
        "Gear": "Gear",
        "PlasmaExciter": "Plasma Exciter",
        "PhotonCombiner": "Photon Combiner",
        "ElectromagneticTurbine": "Electromagnetic Turbine",
        "Processor": "Processor",
        "AnnihilationConstraintSphere": "Annihilation Constraint Sphere",
        "TitaniumGlass": "Titanium Glass",
        "ParticleBroadband": "Particle Broadband",
        "LogisticsDrone": "Logistics Drone",
        "UnipolarMagnet": "Unipolar Magnet",
        "Foundation": "Foundation",
        "CriticalPhoton": "Critical Photon",
        "ParticleContainer": "Particle Container",
        "SuperMagneticRing": "Super Magnetic ring",
        "GravitonLens": "Graviton Lens",
        "SpaceWarper": "Space Warper",
        "PlaneFilter": "Plane Filter",
        "QuantumChip": "Quantum Chip",
        "LogisticsVessel": "Logistics Vessel",
        "Log": "Log",
        "ElectromagneticMatrix": "Electromagnetic Matrix",
        "EnergyMatrix": "Energy Matrix",
        "StructureMatrix": "Structure Matrix",
        "InformationMatrix": "Information Matrix",
        "GravityMatrix": "Gravity Matrix",
        "UniverseMatrix": "Universe Matrix",
        "SolarSail": "Solar Sail",
        "FrameMaterial": "Frame Material",
        "DysonSphereComponent": "Dyson Sphere Component",
        "SmallCarrierRocket": "Small Carrier Rocket",
        "PlantFuel": "Plant Fuel",
        "TeslaTower": "Tesla Tower",
        "WirelessPowerTower": "Wireless Power Tower",
        "SatelliteSubstation": "Satellite Substation",
        "WindTurbine": "Wind Turbine",
        "ThermalPowerStation": "Thermal Power Station",
        "SolarPanel": "Solar Panel",
        "MiniFusionPowerStation": "Mini Fusion Power Station",
        "Accumulator": "Accumulator",
        "FullAccumulator": "Full Accumulator",
        "EnergyExchanger": "Energy Exchanger",
        "RayReceiver": "Ray Receiver",
        "ArtificialStar": "Artificial Star",
        "ConveyorMK1": "Conveyor Mk. 1",
        "ConveyorMK2": "Conveyor Mk. 2",
        "ConveyorMK3": "Conveyor Mk. 3",
        "Splitter": "Splitter",
        "StorageMK1": "Storage Mk. 1",
        "StorageMK2": "Storage Mk. 2",
        "PlanetaryLogisticsStation": "Planetary Logistics Station",
        "InterstellarLogisticsStation": "Interstellar Logistics Station",
        "OrbitCollector": "Orbit Collector",
        "EMRailEjector": "Em Rail ejector",
        "SorterMK1": "Sorter Mk. 1",
        "SorterMK2": "Sorter Mk. 2",
        "SorterMK3": "Sorter Mk. 3",
        "MiningMachine": "Mining Machine",
        "OilExtractor": "Oil Extractor",
        "OilRefinery": "Oil Refinery",
        "MiniatureParticleCollider": "Miniature Particle Collider",
        "MatrixLab": "Matrix Lab",
        "VerticalLaunchingSilo": "Vertical Launching Silo",
        "AssemblingMachineMK1": "Assembling Machine Mk. 1",
        "AssemblingMachineMK2": "Assembling Machine Mk. 2",
        "AssemblingMachineMK3": "Assembling Machine Mk. 3",
        "Smelter": "Smelter",
        "ChemicalPlant": "Chemical Plant",
        "Fractionator": "Fractionator",
    },
    technology: {
        "DysonSphereProgram": "Dyson Sphere Program",
        "Electromagnetism": "Electromagnetism",
        "BasicLogisticsSystem": "Basic Logistics System",
        "AutomaticMetallurgy": "Automatic Metallurgy",
        "ElectromagneticMatrix": "Electromagnetic Matrix",
        "BasicAssemblingProcesses": "Basic Assembling Processes",
        "FluidStorageEncapsulation": "Fluid Storage Encapsulation",
        "HighEfficiencyPlasmaControl": "High Efficiency Plasma Control",
        "ElectromagneticDrive": "Electromagnetic Drive",
        "ImprovedLogisticsSystem": "Improved Logistics System",
        "SteelSmelting": "Steel Smelting",
        "SmeltingPurification": "Smelting Purification",
        "ThermalPower": "Thermal Power",
        "PlasmaExtractRefining": "Plasma Extract Refining",
        "AccelerantMK1": "Accelerant Mk. 1",
        "EnvironmentModification": "Environment Modification",
        "CrystalSmelting": "Crystal Smelting",
        "SolarCollection": "Solar Collection",
        "SemiconductorMaterial": "Semiconductor Material",
        "DeuteriumFractionation": "Deuterium Fractionation",
        "BasicChemicalEngineering": "Basic Chemical Engineering",
        "EnergyMatrix": "Energy Matrix",
        "MagneticLevitationTechnology": "Magnetic Levitation Technology",
        "HighEfficiencyLogisticsSystem": "High Efficiency Logistics System",
        "TitaniumSmelting": "Titanium Smelting",
        "EnergyStorage": "Energy Storage",
        "PhotonFrequencyConversion": "Photon Frequency Conversion",
        "Processor": "Processor",
        "AppliedSuperconductor": "Applied Superconductor",
        "PolymerChemicalEngineering": "Polymer Chemical Engineering",
        "XRayCracking": "X Ray Cracking",
        "HydrogenFuelRod": "Hydrogen Fuel Rod",
        "SuperMagneticFieldGenerator": "Super Magnetic Field Generator",
        "PlanetaryLogisticsSystem": "Planetary Logistics System",
        "SolarSailOrbitSystem": "Solar Sail Orbit System",
        "HighSpeedAssemblingProcesses": "High Speed Assembling Processes",
        "HighStrengthCrystal": "High Strength Crystal",
        "Thruster": "Thruster",
        "AccelerantMK2": "Accelerant Mk. 2",
        "MagneticParticleTrap": "Magnetic Particle Trap",
        "HighStrengthTitaniumAlloy": "High Strength Titanium Alloy",
        "HighStrengthLightweightStructure": "High Strength Lightweight Structure",
        "RayReceiver": "Ray Receiver",
        "MiniFusionPowerGeneration": "Mini Fusion Power Generation",
        "HighStrengthMaterial": "High Strength Material",
        "StructureMatrix": "Structure Matrix",
        "ReinforcedThruster": "Reinforced Thruster",
        "InterstellarLogisticsSystem": "Interstellar Logistics System",
        "InterstellarPowerTransmission": "Interstellar Power Transmission",
        "ParticleControlTechnology": "Particle Control Technology",
        "HighStrengthGlass": "High Strength Glass",
        "CasimirCrystal": "Casimir Crystal",
        "MiniatureParticleCollider": "Miniature Particle Collider",
        "AccelerantMK3": "Accelerant Mk. 3",
        "SatellitePowerDistributionSystem": "Satellite Power Distribution System",
        "GasGiantsExplotiation": "Gas Giants Explotiation",
        "InformationMatrix": "Information Matrix",
        "WaveFunctionInterference": "Wave Function Interference",
        "StrangeMatter": "Strange Matter",
        "VerticalLaunchingSilo": "Vertical Launching Silo",
        "QuantumChip": "Quantum Chip",
        "GravitationalWaveRefraction": "Gravitational Wave Refraction",
        "DysonSphereStressSystem": "Dyson Sphere Stress System",
        "PlanetaryIonosphereUtilization": "Planetary Ionosphere Utilization",
        "QuantumPrintingTechnology": "Quantum Printing Technology",
        "GravityMatrix": "Gravity Matrix",
        "DiracInversionMechanism": "Dirac Inversion Mechanism",
        "ControlledAnnihilationReaction": "Controlled Annihilation Reaction",
        "ArtificialStar": "Artificial Star",
        "UniverseMatrix": "Universe Matrix",
        "MissionCompleted": "Mission Completed",
    },
    producers: {
        "AssemblingMachine": "Assembling Machine",
        "Smelter": "Smelter",
        "OilRefinery": "Oil Refinery",
        "ChemicalPlant": "ChemicalPlant",
        "Fractionator": "Fractionator",
        "ToDo": "<This recipe is NYI>",
    },
    other: {
        title: "Center Brain Archive",
        instructions: "Left-click on an item to see all the ways to produce it.<br>Right-click to see all the ways to use it.",

        productionMethods(item: Item) {
            return `Ways to produce ${English.items[item]}`;
        },
        consumptionMethods(item: Item) {
            return `Ways to consume ${English.items[item]}`;
        },
        unknownItem(item: string) {
            return `Unknown item <code>${item}</code>`;
        },

        craftinfo(time: number, madeIn: Producer, handcraftable: boolean) {
            return `${time.toPrecision(1)} seconds, ${English.producers[madeIn]}, ${handcraftable ? "Handcraftable" : "Not Handcraftable"}`;
        },
        unlockedBy(tech: Technology) {
            return `Unlocked by ${English.technology[tech]}`;
        },
        recipeID(recipe: Recipe) {
            return "Recipe ID: " + recipe;
        },
        unknownRecipeID(recipe: string) {
            return `Unknown recipe ID <code>${recipe}</code>`;
        }
    }
};