use enum_map::Enum;
use schemars::JsonSchema;
use serde::Serialize;

#[derive(Debug, Clone, Copy, Enum, Serialize, JsonSchema)]
pub enum Recipe {
    IronSmelting,
    CopperSmelting,
    SiliconSmelting,
    StoneSmelting,
    GraphiteSmelting,
    PlasmaRefining,
    Plastic,
    GrapheneFromFireIce,
    GrapheneFromGraphiteAndSulfuric,
    MagnetSmelting,
    Electromagnet,
    CrystalSiliconFromIngot,
    CrystalSiliconFromFractal,
    GlassSmelting,
    DiamondFromGraphite,
    DiamondFromKimberlite,
    XRayCracking,
    OrganicCrystalFromWood,
    OrganicCrystalFromPlastic,
    HydrogenFuelRod,
    SteelSmelting,
    SiliconOreFromStone,
    CircuitBoard,
    SulfuricAcidFromStone,
    PlasmaExciter,
    Processor,
    PhotonCombinerFromPrism,
    PhotonCombinerFromCrystal,
    MicrocrystallineComponent,
    ElectromagneticMatrix,
    EnergyMatrix,
    Foundation,

    TeslaTower,
    WirelessPowerTower,
    WindTurbine,
    ThermalPowerStation,
    SolarPanel,
    ConveyorMK1,
    Splitter,
    StorageMK1,
    FluidStorage,
    SorterMK1,
    SorterMK2,
    MiningMachine,
    WaterPump,
    OilExtractor,
    OilRefinery,
    AssemblingMachineMK1,
    Smelter,
    Fractionator,
    ChemicalPlant,
    MatrixLab,
}
